services:
  web:
    container_name: youtube_video_downloader_web
    image: piaseckijulian/youtube_video_downloader_web
    depends_on:
      - api
    build: ./web
    ports:
      - "5173:5173"
    volumes:
      - ./web/.svelte-kit:/app/.svelte-kit
    develop:
      watch:
        - path: ./web/package.json
          action: rebuild

        - path: ./pnpm-lock.yaml
          action: rebuild

        - path: ./web
          target: /app
          action: sync

  api:
    container_name: youtube_video_downloader_api
    image: piaseckijulian/youtube_video_downloader_api
    build: ./api
    env_file: ./api/.env
    ports:
      - "8000:8000"
    develop:
      watch:
        - path: ./api/requirements.txt
          action: rebuild

        - path: ./api
          target: /app
          action: sync
