services:
  web:
    container_name: youtube_video_downloader_web
    image: youtube_video_downloader_web_image
    depends_on:
      - api
    build: ./web
    ports:
      - '5173:5173'
    environment:
      API_URL: 'http://api:5000'
    volumes:
      - ./web/.svelte-kit:/app/.svelte-kit
    develop:
      watch:
        - path: ./web/package.json
          action: rebuild

        - path: ./web/pnpm-lock.yaml
          action: rebuild

        - path: ./web
          target: /app
          action: sync

  api:
    container_name: youtube_video_downloader_api
    image: youtube_video_downloader_api_image
    build: ./api
    ports:
      - '5000:5000'
    develop:
      watch:
        - path: ./api/requirements.txt
          action: rebuild

        - path: ./api
          target: /app
          action: sync
